name: Build & Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:

  build:

    name: Build

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Package
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/

  deploy:

    name: Deploy

    needs:
      - build

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    if: |
      github.event_name != 'pull_request' && github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
